public with sharing class {{ api_name }} implements ITriggerHandler{
	public {{ api_name }}() {
		
	}
	
	// *************** Constants
	
	// *************** Class Members
	
	// *************** Constructors
	public TargetProfileConfigurationTriggerHandler() {}
	
	// *************** Unused
	public void beforeDelete(SObject so) {}	
	public void afterDelete(SObject so) {}
	
	// *************** Bulk
	public void bulkBefore() {
	
	}
		
	public void bulkAfter() {
	
	}
	
	// *************** Before
	public void beforeInsert(SObject so) {
	
	}
	
	public void beforeUpdate(SObject oldSo, SObject so) {
	
	}
	
	// *************** After
	public void afterInsert(SObject so) {
	
	}
	
	public void afterUpdate(SObject oldSo, SObject so) {
		
	}
	
	// *************** Finally
	public void andFinally() {
	
	}
}
